name: Generate Snake Animation

on:
  # Runs the job at 6am UTC daily
  schedule:
    - cron: "0 6 * * *"
  # Allows you to manually run the workflow
  workflow_dispatch:
  # Triggers the workflow on each commit to the readme
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository contents
      - name: Checkout
        uses: actions/checkout@v2

      # Generate the snake animation
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: YOUR_GITHUB_USERNAME
          outputs: dist/snake.svg

      # Push the snake animation to the repository
      - name: Upload Snake Animation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
